version: "3.9"

services:
  api:
    build:
      context: ../test_deploy
    image: maksnd/test_deploy # образ из docker hub
    ports:
      - 80:80
    volumes:
      - ~/sqlite_database:/code/instance
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ps_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

