version: "3.9"

services:
  api:
    build: # 'это означает что образ должен быть собран из папки проекта
      context: ../test_deploy
    image: maksnd/test_deploy # образ из docker hub
    ports:
      - 80:80
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@pg/ps_db
    volumes:
      - ~/sqlite_database:/code/instance
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres # это означает что должен быть запущен существующий образ
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ps_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

