version: "3.9"

services:
  api:
    image: maksnd/test_deploy:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
#      POSTGRES_USER: $DB_USER
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

