name: Build and deploy workflow # дадим название нашему workflow
on: [push] # событие по которому запустится workflow
jobs:
  build_and_push: # первая часть - часть CI
    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls -la
      - name: clone code
        uses: actions/checkout@v2
      - name: list dir 2
        run: ls -la

